name: Build Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        yarn install && yarn build
        xcodebuild -scheme 'CompoundTokens' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
